### ISSUE TITLE
gnu(3600)=4484 duration : about 36 minutes

### ISSUE THREAD

**Issue by gnufinder** [alex-konovalov/gnu#20] opened 2016-05-15 15:50 UTC

**Comment by olexandr-konovalov** [comment] 2016-05-15 17:51
Validated on Azure cloud standard DS3 v2 instance (4 cores, 14 GB RAM)

gnu(3600) = 4484

GAP      4.8.3
GrpConst 2.5
CubeFree 1.15
SglPPow  1.1
Runtime: 1279164 ms
Isomorphic groups eliminated

**Comment by olexandr-konovalov** [comment] 2016-05-18 21:03
Closed as a duplicate of #15.

**Closed as completed by olexandr-konovalov** 2016-05-18 21:03 UTC
Labels: duplicate, replicated
