### ISSUE TITLE
gnu(2592)=24562

### ISSUE THREAD

**Issue by gnufinder** [alex-konovalov/gnu#23] opened 2016-05-17 17:38 UTC
Calculation took 20 minutes. No lists were returned. 

gap> time/60000*1.0;
19.8119
gap> Size(x);Collected(List(x,Size));ForAll(x,IsGroup);
24562
[ [ 2592, 24562 ] ]
true
gap>

**Comment by olexandr-konovalov** [comment] 2016-05-17 22:06
This is the final part of the output of output of `grpconst.sh 2592`:

```
GAP      4.8.3
GrpConst 2.5
CubeFree 1.15
SglPPow  1.1
Runtime: 5479727 ms
Isomorphic groups eliminated
gnu(2592) = 24562
```

so this took about 90 minutes on Linux server (AMD Opteron 6376 1400 MHz processor, 512 GB RAM). 
@gnufinder, are you sure with your timings? would be good to see what was the actual value returned by `time;`. If it's 20 minutes, which versions of GAP and GrpConst do you use?

**Comment by gnufinder** [comment] 2016-05-18 19:18
GAP-version : 4.7.9.
grp-const-version : 2.3.

**Comment by olexandr-konovalov** [comment] 2016-05-18 19:28
@gnufinder thanks - I will try to reproduce this, then ask @hulpke if he has an idea. As you know, he improved some heuristics in the core GAP system and now GAP 4.8 is able to handle some cases much faster, but maybe this is the case where they have an inverse side-effect ...

**Comment by olexandr-konovalov** [comment] 2016-05-18 21:10
Reopened because of the performance regression that should be investigated.

**Comment by olexandr-konovalov** [comment] 2016-05-19 09:06
@gnufinder: to share some thoughts about the importance of stating version information. It looks like all your recent submissions were produced with GAP 4.7.9 and GrpConst 2.3, while I was verifying them with GAP 4.8.3 and GrpConst 2.5. While I normally recommend all users to upgrade to the newest GAP release as soon as possible, I consider the fact that your installation was outdated quite useful. We got even more knowledge that we have asked, since we now know for the reported n that there are no discrepancies in the values of gnu(n) returned by both versions.

I think one should never ignore the rule of providing details of your GAP installation. I'm working on making this easier in #27 and #28 so that one could call a function, paste the output and only add the description of the computer and operating system. See also more at https://github.com/alex-konovalov/gnu/blob/master/CONTRIBUTING.md.

**Comment by olexandr-konovalov** [comment] 2016-05-20 12:41
@gnufinder would you be able to try this again with GAP 4.7.9 and measure the real time? (in case this is a timer overflow on Windows, see comments in #39).

**Comment by olexandr-konovalov** [comment] 2016-05-20 20:29
I have installed GAP 4.7.9 on the same Linux server which was used to validate this with GAP 4.8.3 earlier (AMD Opteron 6376 1400 MHz processor, 512 GB RAM):

gnu(2592)=24562

GAP      4.7.9
GrpConst 2.3
Runtime: 5676862 ms
Isomorphic groups eliminated

So in these two observations the runtime  with GAP 4.8.3 is 5479.727s and with GAP 4.7.9 it is 5676.862s, so the new release is even 3 minutes faster. This should be a timer overflow (see #39) and not a speed regression. Hence I am removing the "regression" label and closing this issue.

**Closed as completed by olexandr-konovalov** 2016-05-20 20:29 UTC
Labels: replicated, new! (for n< 50000)
