### ISSUE TITLE
gnu(3136)>8077

### ISSUE THREAD

**Issue by gnufinder** [alex-konovalov/gnu#95] opened 2016-05-25 09:19 UTC
gap> time/60000*1.0;
61.039
gap> Size(x);
8081
gap> Collected(List(x,Size));
[ [ 2, 4 ], [ 3136, 8077 ] ]
gap> ForAll(x,IsGroup);
false
gap>

Calculation was done with GAP 4.8.3 using the package GrpConst 2.5 and took 61 minutes. 8077 groups and 4 pairs of groups were returned. I use Windows Vista.

**Comment by olexandr-konovalov** [comment] 2016-05-25 09:27
Thank you @gnufinder: this is a duplicate of #88, so you can just repost this as a comment there.

By the way, it was safe to state that gnu(3136)>8081 = Length(x) since each of the sublists results in at least one group.

**Comment by gnufinder** [comment] 2016-05-25 09:30
I already submitted this gnu, but I was not sure about the status of gnu(3136). At least, it is an additional verification.

**Comment by olexandr-konovalov** [comment] 2016-05-25 09:32
@gnufinder exactly - this is very much in the scope of this project. As README.md says, "verifying existing entries (possibly using other hardware, operating systems, new releases of GAP and related packages)" is a useful contribution. My point is just that it's good to keep such records in one place.

**Comment by gnufinder** [comment] 2016-05-25 09:36
I would like to present the candidates for gnu(n)=n , but I am not sure whether the place suffices.

**Closed as completed** 2016-05-25 09:47 UTC
Labels: duplicate
