### ISSUE TITLE
gnu(3360)=7740

### ISSUE THREAD

**Issue by gnufinder** [alex-konovalov/gnu#66] opened 2016-05-23 07:16 UTC
n     : 3360
gnu : 7740

no lists returned
duration : about 2 hours
method : grpconst

**Comment by olexandr-konovalov** [comment] 2016-05-23 12:36
This is also provided by @markuspf in #75 - will process both after replication.

**Comment by olexandr-konovalov** [comment] 2016-05-23 21:49
Thank you for this submissio. I've closed it as a duplicate of #75 and left a note there.

**Closed as completed by olexandr-konovalov** 2016-05-23 21:49 UTC
Labels: duplicate
